In [1]:
import numpy as np

In [4]:
print(np.__version__)
#np.show_config()

1.16.4


In [5]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
z = np.arange(50)
z = z[::-1]

In [11]:
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [20]:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
z = np.random.random((3,3,3))
print(z)

[[[0.231781   0.17375078 0.11862172]
  [0.83444138 0.34260369 0.19849012]
  [0.94830053 0.11579829 0.05183199]]

 [[0.52880789 0.33840758 0.72633415]
  [0.40725931 0.24468607 0.68649523]
  [0.80012115 0.65343827 0.1373515 ]]

 [[0.48367313 0.45108987 0.04738524]
  [0.88008993 0.09115743 0.71718823]
  [0.85995391 0.31792477 0.5737613 ]]]


In [25]:
z = np.random.random((10,10))
zmin, zmax = z.min(), z.max()
print(zmin, zmax)

0.02388271461634761 0.9992685752654862


In [26]:
print(z)

[[0.73392181 0.24027687 0.49833777 0.93619427 0.57212267 0.54062554
  0.96225895 0.34150434 0.8882178  0.40234083]
 [0.29726418 0.75808498 0.5179047  0.6178098  0.99926858 0.65397825
  0.23941138 0.85697282 0.32816873 0.25616225]
 [0.18757049 0.91134893 0.1416988  0.65549942 0.22923816 0.42003008
  0.13014647 0.08718524 0.54567046 0.84315615]
 [0.41450199 0.62282028 0.13631922 0.65777476 0.78649713 0.7087001
  0.84293213 0.36415647 0.98987393 0.30970548]
 [0.77272733 0.18106071 0.08015225 0.1416387  0.8375416  0.78978627
  0.84717263 0.17350998 0.23156818 0.82745584]
 [0.34769571 0.30385386 0.56223003 0.92702426 0.12388947 0.19485143
  0.12662463 0.9288446  0.26623276 0.3160169 ]
 [0.84691851 0.9902905  0.73971894 0.42492037 0.14664303 0.77317636
  0.05712649 0.3094305  0.85945823 0.21555021]
 [0.9771195  0.95875612 0.12898972 0.35033788 0.54991084 0.28309641
  0.74902951 0.35495925 0.81743391 0.96832753]
 [0.53869973 0.2127735  0.02388271 0.96126317 0.97895349 0.24891403
  0.52859024 

In [27]:
z = np.random.random(30)
m = z.mean()
print(m)

0.5131084487723493


In [32]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [40]:
0*np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3*0.1

False

In [42]:
z = np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [48]:
z=np.zeros((8,8), dtype=int)
z[::2,1::2] = 1
z[1::2,::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [49]:
z = np.tile(np.array([[0,1],[1,0],]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [50]:
z = np.random.random((5,5))
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
print(z)

[[0.85771253 0.32970152 0.40893566 0.13175699 0.02887559]
 [0.02817888 0.23532549 0.11463779 0.0643499  0.        ]
 [0.36823772 0.77675552 0.27424101 0.8785856  0.94327614]
 [0.49399823 0.09700965 1.         0.6224356  0.02940244]
 [0.48787561 0.13596518 0.46061895 0.11136196 0.0218214 ]]
